### ISSUE TITLE
Protect device unsupported?

### ISSUE THREAD

**Issue by barcar** [jamesog/nest_exporter#1]
The docs state that Protect devices are supported, but I am seeing the following:

`2024-03-02T10:23:35Z WRN unsupported device type | type=protect `

Is Protect support actually implemented? Or has something changed since the last release?

Thanks.

**Comment by jamesog** [comment]
The checkbox next to everything except Nest Thermostat is not checked, meaning not yet implemented. I only have access to a Nest Thermostat, so the rest is yet to be implemented.
